module.exports = {
  ChannelNameChange: 'スレッドチャンネルの名前が変更されました',
  ChannelPinnedMessage: 'メッセージがピン留めされました',
  AutoModerationAction: 'Automodが実行されました',
  ChannelFollowAdd: 'チャンネルがフォローされました',
  ChatInputCommand: 'スラッシュコマンドです',
  ContextMenuCommand: 'コンテキストメニューコマンドです',
  GuildApplicationPremiumSubscription: 'サーバーがブーストされました',
  GuildBoost: 'サーバーがブーストされました',
  GuildBoostTier1: 'サーバーブーストレベルが 1 に達しました',
  GuildBoostTier2: 'サーバーブーストレベルが 2 に達しました',
  GuildBoostTier3: 'サーバーブーストレベルが 3 に達しました',
  UserJoin: '新しいユーザーがサーバーに参加しました',
  PollResult: '投票結果が終了しました',
  StageStart: 'ステージが開始されました',
  StageEnd: 'ステージが終了しました',
  GuildIncidentReportRaid: 'Raid通知です',
  GuildIncidentAlertModeEnabled: 'セキュリティ措置が有効になりました',
  GuildIncidentReportFalseAlarm: 'セキュリティ措置が解除されました',
  StageSpeaker: '新しいスピーカーがステージに追加されました',
  default: null,
};