module.exports.selectionMap = {
    'all': '全曲',
    'level10': '☆10',
    'edit': '裏譜面のみ',
    'pops': 'ポップス',
    'anime': 'アニメ',
    'kids': 'キッズ',
    'vocalo': 'ボーカロイド',
    'variety': 'バラエティ',
    'classic': 'クラシック',
    'namco': 'ナムコオリジナル',
    'pops': 'POPS&アニメ',
    'niconico': 'niconico&ボーカロイド',
    'toho': '東方Project',
    'gekichu': 'オンゲキ&チュウニズム',
    'remaster': 'Re:MASTER',
    'utage': '宴会場',
    'irodori': 'イロドリミドリ',
    'gekimai': 'ゲキマイ',
    'original': 'オリジナル',
    'we': 'WORLD\'S END',
    'ultima': 'ULTIMA',
    'social': 'ソーシャルミュージック',
    'virtual': 'Virtual',
    'inf': 'INF譜面',
  };  